name: CI


on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SONAR_PROJECT_KEY: CaioSeniuk_aula-pipeline
      SONAR_ORGANIZATION: caioseniuk
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4
        
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install --legacy-peer-deps
      - name: SonarCloud — Prepare
        shell: bash
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cat > sonar-project.properties <<EOF
          sonar.projectKey=${SONAR_PROJECT_KEY}
          sonar.organization=${SONAR_ORGANIZATION}
          sonar.sources=.
          sonar.tests=.
          sonar.javascript.lcov.reportPaths=coverage/lcov.info
          EOF

      - name: Verificar qualidade
        run: npx eslint .

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >-
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.sources=.
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info